<?php
$title = 'Edit Profile';
$this->headTitle($title);
?>
    <h1 xmlns="http://www.w3.org/1999/html"><?php echo $this->escapeHtml($title); ?></h1><?php
$form = $this->form;
//$form->setAttribute('action', $this->url("/user/profile/" . $this->$user . "/edit", array(), true));
$form->prepare();

$form->get('submit')->setValue('Save Profile');

echo $this->form()->openTag($form);

echo $this->formCollection($form);

echo $this->form()->closeTag();

