<?php

$title = 'Profile';
$this->headTitle($title);

?>
<h1 xmlns="http://www.w3.org/1999/html"><?php echo $this->escapeHtml($title); ?></h1>
<a href="<?php echo "/user/edit/" . $user->getId(); ?>">Editar</a>
<p>
    <h5><?php echo "Username &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
        if (is_null($user->getUsername())) echo "Not set";
        else echo $this->escapeHtml($user->getUsername());?></h5>

    <h5><?php echo "Name &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
        if (is_null($profile['nombre'])) echo "Not set";
        else echo $this->escapeHtml($profile['nombre']);?></h5>

    <h5><?php echo "Surname &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
        if (is_null($profile['apellidos'])) echo "Not set";
        else echo $this->escapeHtml($profile['apellidos']);?></h5>

<!--    <h5>--><?php //echo "Date of birth &nbsp;&nbsp;";
//        if (is_null($profile['fecha_nacimiento'])) echo "Not set";
//        else echo $this->escapeHtml($profile['fecha_nacimiento']);?><!--</h5>-->
<!---->
<!--    <h5>--><?php //echo "Email &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
//        if (is_null($user->getMail())) echo "Not set";
//        else echo $this->escapeHtml($user->getMail());?><!--</h5>-->

<br /><br />
<h1><?php echo "My tags" ?></h1><a href="#">New tag</a>

<?php foreach ($this->companies as $company): ?>
    <h3><?php echo "Company · " . $company['id_comercializador'] . " "; ?></h3>
    <a href="<?php echo "/servicio/add"; ?>">Add new service</a><br /><br />

    <table class="table">
        <tr>
            <th>Service Name</th>
            <th>Status</th>
        </tr>
        <?php foreach ($this->services as $service): ?>
            <tr>
                <?php //print_r($service) ?>
                <td><?php echo $service['id_servicio']; ?></td>
                <td>
                    <input type="button" id="active" value="Active" />
                    <input type="button" id="inactive" value="Inactive" disabled="disabled" />
                </td>
            </tr>

        <?php endforeach; ?>
    </table>
<?php endforeach; ?>

