<?php

$title = 'Profile';
$this->headTitle($title);

?>
<h1 xmlns="http://www.w3.org/1999/html"><?php echo $this->escapeHtml($title); ?></h1>
<a href="<?php echo "/user/edit/" . $user->getId(); ?>">Editar</a>
<p>
    <h5><?php echo "Username &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
        if (is_null($user->getUsername())) echo "Not set";
        else echo $this->escapeHtml($user->getUsername());?></h5>

    <h5><?php echo "Name &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
        if (is_null($profile['nombre'])) echo "Not set";
        else echo $this->escapeHtml($profile['nombre']);?></h5>

    <h5><?php echo "Surname &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
        if (is_null($profile['apellidos'])) echo "Not set";
        else echo $this->escapeHtml($profile['apellidos']);?></h5>

<!--    <h5>--><?php //echo "Date of birth &nbsp;&nbsp;";
//        if (is_null($profile['fecha_nacimiento'])) echo "Not set";
//        else echo $this->escapeHtml($profile['fecha_nacimiento']);?><!--</h5>-->
<!---->
<!--    <h5>--><?php //echo "Email &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
//        if (is_null($user->getMail())) echo "Not set";
//        else echo $this->escapeHtml($user->getMail());?><!--</h5>-->

<br />
<h1><?php echo "My tags" ?></h1><a href="#">New tag</a>
<br /><br />
<table class="table">
    <tr>
        <th>Tag ID</th>
    </tr>
    <?php foreach ($this->tags as $tag):?>
        <tr>
            <td><?php echo tag['id']; ?></td>
        </tr>
    <?php endforeach; ?>
</table>

<h1><?php echo "Services" ?></h1>
<br />
    <table id="theDude" class="table">
        <tr>
            <th>Service Name</th>
            <th>Status</th>
        </tr>
        <?php foreach ($this->services as $service):?>
            <tr>
                <td><?php echo $service['nombre']; ?></td>
                <td>
                    <?php $par1 = "bt".$service['id_servicio']."_active" ?>
                    <?php $par2 = "bt".$service['id_servicio']."_inactive" ?>
                    <input type="button" class="btn1" value="Active" />
                    <input type="button" class="btn2" value="Inactive" disabled="disabled" />

                </td>
            </tr>
        <?php endforeach; ?>
    </table>

<?php
$this->inlineScript()->captureStart();
echo <<<JS

var theParent = document.getElementById('theDude');
theParent.addEventListener('click', changeStatus, false);

function changeStatus(e) {
    if (e.target !== e.currentTarget) {
        var clickedItem = e.target.class;
        $(clickedItem).attr("disabled", "disabled");
        
    }
    e.stopPropagation();
    }
JS;
$this->inlineScript()->captureEnd();
?>


