<?php

/**
 * Generated by ZF2ModuleCreator
 */

return array(

    'view_manager' => array(
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
    ),

    'controllers' => array(
//        'invokables' => array(
//            'Comercializador\Controller\Comercializador' => 'Comercializador\Controller\ComercializadorController',
//            'Comercializador\Controller\List' => 'Comercializador\Controller\ListController',
//        ),
        'factories' => array(
            'Comercializador\Controller\List' => 'Comercializador\Factory\ListControllerFactory',
        )
    ),

    'service_manager' => array(
        'factories' => array(
            'Comercializador\Mapper\ComercializadorMapperInterface'   
                    => 'Comercializador\Factory\ZendDbSqlMapperFactory',
            'Comercializador\Service\ComercializadorServiceInterface' 
                    => 'Comercializador\Factory\ComercializadorServiceFactory',
            'Zend\Db\Adapter\Adapter'           => 'Zend\Db\Adapter\AdapterServiceFactory'
        )
    ),

    'router' => array(
// Uncomment below to add routes
        'routes' => array(
            'comercializador' => array(
                'type' => 'Literal',
                'options' => array(
                    'route' => '/comercializador',
                    'defaults' => array(
                        '__NAMESPACE__' => 'Comercializador\Controller',
                        'controller' => 'List',
                        'action' => 'index',
                    )
                )
            )
        ),
        'may_terminate' => true,
        'child_routes' => array(
            'default' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/[:controller[/:action]]',
                    'constraints' => array(
                        'controller' => '[a-zA-Z][a-zA-Z0-9_-]*',
                        'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
                    )
                )
            )
        )
    )
);