<?php

/**
 * Generated by ZF2ModuleCreator
 */

$tuto =  array(
    'controllers' => array(
        'invokables' => array(
            'Alex\Controller\Alex' => 'Alex\Controller\AlexController',
        ),
    ),
    // The following section is new and should be added to your file
    'router' => array(
        'routes' => array(
            'alex' => array(
                'type'    => 'segment',
                'options' => array(
                    'route'    => '/alex[/:action][/:id]',
                    'constraints' => array(
                        'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
                        'id'     => '[0-9]+',
                    ),
                    'defaults' => array(
                        'controller' => 'Alex\Controller\Alex',
                        'action'     => 'index',
                    ),
                ),
            ),
        ),
    ),

    'view_manager' => array(
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
    ),
);

$default =  array(

    'view_manager' => array(
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
    ),

    'controllers' => array(
        'invokables' => array(
            'Alex\Controller\Alex' => 'Alex\Controller\AlexController',

        ),
    ),

    'service_manager' => array(

    ),

    'router' => array(
// Uncomment below to add routes
        'routes' => array(
            'alex' => array(
                'type' => 'Literal',
                'options' => array(
                    'route' => '/alex',
                    'defaults' => array(
                        '__NAMESPACE__' => 'Alex\Controller',
                        'controller' => 'Alex',
                        'action' => 'index',
                    )
                )
            )
        ),
        'may_terminate' => true,
        'child_routes' => array(
            'alex' => array(
                'type' => 'literal',
                'options' => array(
                    'route' => 'alex',
                    'defaults' => array(
                        'controller' => 'Alex\Controller\AlexController',
                        'action' => 'alex',
                    ),
                ),
            ),

//            'default' => array(
//                'type' => 'Segment',
//                'options' => array(
//                    'route' => '/[:controller[/:action]]',
//                    'constraints' => array(
//                        'controller' => '[a-zA-Z][a-zA-Z0-9_-]*',
//                        'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
//                    )
//                )
//            ),
//
//            'default' => array(
//                'type' => 'Segment',
//                'options' => array(
//                    'route' => '/[:controller[/:action]]',
//                    'constraints' => array(
//                        'controller' => '[a-zA-Z][a-zA-Z0-9_-]*',
//                        'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
//                    )
//                )
//            ),
        )
    )
);

$default2 =  array(

    'view_manager' => array(
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
    ),

    'controllers' => array(
        'invokables' => array(
            'Alex\Controller\Alex' => 'Alex\Controller\AlexController',

        ),
    ),

    'service_manager' => array(

    ),

    'router' => array(
// Uncomment below to add routes
        'route' => array(
            'alex' => array(
                'type' => 'Literal',
                'options' => array(
                    'route' => '/alex',
                    'defaults' => array(
                        '__NAMESPACE__' => 'Alex\Controller',
                        'controller' => 'Alex',
                        'action' => 'index',
                    )
                )
            ),
            'may_terminate' => true,
            'child_routes' => array(
                'alex' => array(
                    'type' => 'literal',
                    'options' => array(
                        'route' => 'alex',
                        'defaults' => array(
                            '__NAMESPACE__' => 'Alex\Controller',
                            'controller' => 'Alex',
                            'action' => 'alex',
                        )
                    ),
                ),
        ),


//            'default' => array(
//                'type' => 'Segment',
//                'options' => array(
//                    'route' => '/[:controller[/:action]]',
//                    'constraints' => array(
//                        'controller' => '[a-zA-Z][a-zA-Z0-9_-]*',
//                        'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
//                    )
//                )
//            ),
//
//            'default' => array(
//                'type' => 'Segment',
//                'options' => array(
//                    'route' => '/[:controller[/:action]]',
//                    'constraints' => array(
//                        'controller' => '[a-zA-Z][a-zA-Z0-9_-]*',
//                        'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
//                    )
//                )
//            ),
        )
    )
);

$tuto2 = array(
    'view_manager' => array(
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
    ),

    'controllers' => array(
        'invokables' => array(
            'Alex\Controller\Alex' => 'Alex\Controller\AlexController',

        ),
    ),

    'service_manager' => array(

    ),

    'router' => array(
        'routes' => array(
            'alex' => array(
                'type' => 'literal',
                'options' => array(
                    'route'    => '/alex',
                    'defaults' => array(
                        '__NAMESPACE__' => 'Alex\Controller',
                        'controller' => 'Alex',
                        'action' => 'index',
                    )
                ),
                // Defines that "/news" can be matched on its own without a child route being matched
                'may_terminate' => true,
                'child_routes' => array(
                    'archive' => array(
                        'type' => 'literal',
                        'options' => array(
                            'route'    => '/alex',
                            'defaults' => array(
                                'action'     => 'alex',
                            ),
                        ),
                    ),
                )
            ),
        )
    ),
);

return $tuto2;