<?php

/**
 * Generated by ZF2ModuleCreator
 */

return array(

    'view_manager' => array(
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
    ),

    'controllers' => array(
        'factories' => array(
            'Servicio\Controller\List'      => 'Servicio\Factory\ListControllerFactory',
            'Servicio\Controller\Write'     => 'Servicio\Factory\WriteControllerFactory',
            'Servicio\Controller\Delete'    => 'Servicio\Factory\DeleteControllerFactory',
        )
    ),

    'service_manager' => array(
        'factories' => array(
            'Servicio\Mapper\ServicioMapperInterface'   => 'Servicio\Factory\ZendDbSqlMapperFactory',
            'Servicio\Service\ServicioServiceInterface' => 'Servicio\Factory\ServicioServiceFactory',
            'Zend\Db\Adapter\Adapter'                   => 'Zend\Db\Adapter\AdapterServiceFactory'
        )
    ),

    'router' => array(
// Uncomment below to add routes
        'routes' => array(
            'servicio' => array(
                'type' => 'Literal',
                'options' => array(
                    'route' => '/servicio',
                    'defaults' => array(
                        '__NAMESPACE__' => 'Servicio\Controller',
                        'controller' => 'List',
                        'action' => 'index',
                    )
                ),
                'may_terminate' => true,
                'child_routes' => array(
                    'default' => array(
                        'type' => 'Segment',
                        'options' => array(
                            'route' => '/[:controller[/:action]]',
                            'constraints' => array(
                                'controller' => '[a-zA-Z][a-zA-Z0-9_-]*',
                                'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
                            )
                        )
                    ),
                    'add' => array(
                        'type' => 'literal',
                        'options' => array(
                            'route'    => '/add',
                            'defaults' => array(
                                'controller' => 'Servicio\Controller\Write',
                                'action'     => 'add'
                            )
                        )
                    ),
                    'edit' => array(
                        'type' => 'segment',
                        'options' => array(
                            'route'    => '/edit/:id',
                            'defaults' => array(
                                'controller' => 'Servicio\Controller\Write',
                                'action'     => 'edit'
                            ),
                            'constraints' => array(
                                'id' => '\d+'
                            )
                        )
                    ),
                    'delete' => array(
                        'type' => 'segment',
                        'options' => array(
                            'route'    => '/delete/:id',
                            'defaults' => array(
                                'controller' => 'Servicio\Controller\Delete',
                                'action'     => 'delete'
                            ),
                            'constraints' => array(
                                'id' => '\d+'
                            )
                        )
                    ),
                )
            )
        ),
    )
);