<?php
// module/Album/view/album/album/index.phtml:
$title = 'Comercializadores';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <!--    <a href="--><?php //echo $this->url('comercializador', array('action' => 'add'); ?><!--">Add new comercializador</a>-->
    <a href="<?php echo $this->url('comercializador/add'); ?>">Add new comercializador</a>
</p>
<table class="table">
    <tr>
        <th>Id</th>
        <th>Username</th>
        <th>Mail</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($this->comercializadores as $comercializador): ?>
        <tr>
            <td><?php echo $this->escapeHtml($comercializador->getId()); ?></td>
            <td><?php echo $this->escapeHtml($comercializador->getUsername()); ?></td>
            <td><?php echo $this->escapeHtml($comercializador->getMail()); ?></td>
            <td>
                <!--                <a href="--><?php //echo $this->url('comercializador', array('action' => 'edit', 'id' => $comercializador->getId())); ?><!--">Edit</a>-->
                <!--                <a href="--><?php //echo $this->url('comercializador', array('action' => 'delete', 'id' => $comercializador->getId())); ?><!--">Delete</a>-->
                <a href=comercializador/edit/<?php echo $comercializador->getId(); ?>>Edit</a>
                <a href=comercializador/delete/<?php echo $comercializador->getId(); ?>>Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
