<?php

/**
 * Generated by ZF2ModuleCreator
 */

return array(

    'view_manager' => array(
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
    ),

    'controllers' => array(
//        'invokables' => array(
//            'Login\Controller\Login' => 'Login\Controller\LoginController',
//        ),
//        'factories' => array(
//            'Login\Controller\Login' => 'Login\Factory\LoginControllerFactory',
//        ),
        'invokables' => array(
            'Login\Controller\Index'   => 'Login\Controller\IndexController',
            'Login\Controller\Auth'    => 'Login\Controller\AuthController',
            'Login\Controller\Success' => 'Login\Controller\SuccessController'
        ),
    ),

    'service_manager' => array(
        'factories' => array(
//            'User\Mapper\UserMapperInterface'   => 'User\Factory\ZendDbSqlMapperFactory',
//            'User\Service\UserServiceInterface' => 'User\Factory\UserServiceFactory',
            'Zend\Db\Adapter\Adapter'           => 'Zend\Db\Adapter\AdapterServiceFactory'
        )
    ),

    'router' => array(
// Uncomment below to add routes
        'routes' => array(
            'login' => array(
                'type' => 'Literal',
                'options' => array(
                    'route' => '/login',
                    'defaults' => array(
                        '__NAMESPACE__' => 'Login\Controller',
                        'controller' => 'Auth',
                        'action' => 'login',
                    )
                ),
                'may_terminate' => true,
                'child_routes' => array(
                    'default' => array(
                        'type' => 'Segment',
                        'options' => array(
                            'route' => '/[:controller[/:action]]',
                            'constraints' => array(
                                'controller' => '[a-zA-Z][a-zA-Z0-9_-]*',
                                'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
                            )
                        )
                    ),

//                    'login' => array(
//                        'type' => 'literal',
//                        'options' => array(
//                            'route'    => '/login',
//                            'defaults' => array(
//                                'controller' => 'Login\Controller\Auth',
//                                'action'     => 'login'
//                            )
//                        )
//                    ),
//                    'dentro' => array(
//                        'type' => 'literal',
//                        'options' => array(
//                            'route'    => '/dentro',
//                            'defaults' => array(
//                                'controller' => 'Login\Controller\Login',
//                                'action'     => 'dentro'
//                            )
//                        )
//                    ),

                    'login' => array(
                        'type'    => 'Literal',
                        'options' => array(
                            'route'    => '/auth',
                            'defaults' => array(
                                '__NAMESPACE__' => 'Login\Controller',
                                'controller'    => 'Auth',
                                'action'        => 'login',
                            ),
                        ),
                        'may_terminate' => true,
                        'child_routes' => array(
                            'process' => array(
                                'type'    => 'Segment',
                                'options' => array(
                                    'route'    => '/[:action]',
                                    'constraints' => array(
                                        'controller' => '[a-zA-Z][a-zA-Z0-9_-]*',
                                        'action'     => '[a-zA-Z][a-zA-Z0-9_-]*',
                                    ),
                                    'defaults' => array(
                                    ),
                                ),
                            ),
                        ),
                    ),

                    'success' => array(
                        'type'    => 'Literal',
                        'options' => array(
                            'route'    => '/success',
                            'defaults' => array(
                                '__NAMESPACE__' => 'Login\Controller',
                                'controller'    => 'Success',
                                'action'        => 'index',
                            ),
                        ),
                        'may_terminate' => true,
                        'child_routes' => array(
                            'default' => array(
                                'type'    => 'Segment',
                                'options' => array(
                                    'route'    => '/[:action]',
                                    'constraints' => array(
                                        'controller' => '[a-zA-Z][a-zA-Z0-9_-]*',
                                        'action'     => '[a-zA-Z][a-zA-Z0-9_-]*',
                                    ),
                                    'defaults' => array(
                                    ),
                                ),
                            ),
                        ),
                    ),

                    'authenticate' => array(
                        'type'    => 'Literal',
                        'options' => array(
                            'route'    => '/authenticate',
                            'defaults' => array(
                                '__NAMESPACE__' => 'Login\Controller',
                                'controller'    => 'Auth',
                                'action'        => 'authenticate',
                            ),
                        ),
                        'may_terminate' => true,
                        'child_routes' => array(
                            'default' => array(
                                'type'    => 'Segment',
                                'options' => array(
                                    'route'    => '/[:action]',
                                    'constraints' => array(
                                        'controller' => '[a-zA-Z][a-zA-Z0-9_-]*',
                                        'action'     => '[a-zA-Z][a-zA-Z0-9_-]*',
                                    ),
                                    'defaults' => array(
                                    ),
                                ),
                            ),
                        ),
                    ),

                    'logout' => array(
                        'type'    => 'Literal',
                        'options' => array(
                            'route'    => '/logout',
                            'defaults' => array(
                                '__NAMESPACE__' => 'Login\Controller',
                                'controller'    => 'Auth',
                                'action'        => 'logout',
                            ),
                        ),
                        'may_terminate' => true,
                        'child_routes' => array(
                            'default' => array(
                                'type'    => 'Segment',
                                'options' => array(
                                    'route'    => '/[:action]',
                                    'constraints' => array(
                                        'controller' => '[a-zA-Z][a-zA-Z0-9_-]*',
                                        'action'     => '[a-zA-Z][a-zA-Z0-9_-]*',
                                    ),
                                    'defaults' => array(
                                    ),
                                ),
                            ),
                        ),
                    ),
                )
            )
        ),

    )
);