<?php

/**
 * Generated by ZF2ModuleCreator
 */

$default =  array(

    'view_manager' => array(
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
    ),

    'controllers' => array(
        'factories' => array(
            'Authenticate\Controller\Auth' =>
                'Authenticate\Factory\Controller\AuthControllerServiceFactory'
        ),
        'invokables' => array(
            'Authenticate\Controller\Success' =>
                'Authenticate\Controller\SuccessController'
        ),
    ),

    'service_manager' => array(
        'factories' => array(
            'AuthStorage' =>
                'Authenticate\Factory\Storage\AuthStorageFactory',
            'AuthService' =>
                'Authenticate\Factory\Storage\AuthenticationServiceFactory',
        ),
    ),

    'router' => array(
// Uncomment below to add routes
        'routes' => array(
            'authenticate' => array(
                'type' => 'Literal',
                'options' => array(
                    'route' => '/authenticate',
                    'defaults' => array(
                        '__NAMESPACE__' => 'Authenticate\Controller',
                        'controller' => 'Auth',
                        'action' => 'index',
                    )
                ),
                'may_terminate' => true,
                'child_routes' => array(


//                    'default' => array(
//                        'type' => 'Segment',
//                        'options' => array(
//                            'route' => '/[:controller[/:action]]',
//                            'constraints' => array(
//                                'controller' => '[a-zA-Z][a-zA-Z0-9_-]*',
//                                'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
//                            )
//                        )
//                    ),

                    'auth' => array(
                        'type'    => 'segment',
                        'options' => array(
                            'route'    => '/auth',
                            'defaults' => array(
                                'action'     => 'index',
                            ),
                        ),
                    ),

                    'logout' => array(
                        'type'    => 'segment',
                        'options' => array(
                            'route'    => '/logout',
                            'defaults' => array(
                                'action'     => 'logout',
                            ),
                        ),
                    ),
                    
                    'success' => array(
                        'type'    => 'segment',
                        'options' => array(
                            'route'    => '/success',
                            'defaults' => array(
                                'controller' => 'Authenticate\Controller\Success',
                                'action'     => 'index',
                            ),
                        ),
                    ),
                    
                )
            )
        ),
    )
);


$tuto =  array(

    //controllers services...
    'controllers' => array(
        'factories' => array(
            'Authenticate\Controller\Auth' =>
                'Authenticate\Factory\Controller\AuthControllerServiceFactory'
        ),
        'invokables' => array(
            'Authenticate\Controller\Success' =>
                'Authenticate\Controller\SuccessController'
        ),
    ),

    //register auth services...
    'service_manager' => array(
        'factories' => array(
            'AuthStorage' =>
                'Authenticate\Factory\Storage\AuthStorageFactory',
            'AuthService' =>
                'Authenticate\Factory\Storage\AuthenticationServiceFactory',
        ),
    ),

    //routing configuration...
    'router' => array(
        'routes' => array(

            'auth' => array(
                'type'    => 'segment',
                'options' => array(
                    'route'    => '/auth[/:action]',
                    'defaults' => array(
                        'controller' => 'Authenticate\Controller\Auth',
                        'action'     => 'index',
                    ),
                ),
            ),

            'success' => array(
                'type'    => 'segment',
                'options' => array(
                    'route'    => '/success[/:action]',
                    'defaults' => array(
                        'controller' => 'Authenticate\Controller\Success',
                        'action'     => 'index',
                    ),
                ),
            ),
        ),
    ),

    //setting up view_manager
    'view_manager' => array(
        'template_path_stack' => array(
            'Authenticate' => __DIR__ . '/../view',
        ),
    ),
);

return $default;