<?php
// module/Album/view/album/album/index.phtml:
$title = 'Srvicios';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
<!--    <a href="--><?php //echo $this->url('album', array('action' => 'add')); ?><!--">Add new comercializador</a>-->
</p>
<table class="table">
    <tr>
        <th>Id</th>
        <th>Username</th>
        <th>Mail</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($this->servicios as $servicio): ?>
        <tr>
            <td><?php echo $this->escapeHtml($servicio->getId()); ?></td>
            <td><?php echo $this->escapeHtml($servicio->getUsername()); ?></td>
            <td><?php echo $this->escapeHtml($servicio->getMail()); ?></td>
<!--            <td>-->
<!--                <a href="--><?php //echo $this->url('album', array('action' => 'edit', 'id' => $album->id)); ?><!--">Edit</a>-->
<!--                <a href="--><?php //echo $this->url('album',
//                    array('action' => 'delete', 'id' => $album->id)); ?><!--">Delete</a>-->
<!--            </td>-->
        </tr>
    <?php endforeach; ?>
</table>
