<?php

/**
 * Generated by ZF2ModuleCreator
 */

$default =  array(

    'view_manager' => array(
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
    ),

    'controllers' => array(
        'factories' => array(
            'LoginAlex\Controller\Login'      => 'LoginAlex\Factory\LoginControllerFactory',
        )
    ),

    'service_manager' => array(
        'factories' => array(
            'LoginAlex\Mapper\LoginMapperInterface'   => 'LoginAlex\Factory\ZendDbSqlMapperFactory',
            'LoginAlex\Service\LoginServiceInterface' => 'LoginAlex\Factory\LoginServiceFactory',
            'Zend\Db\Adapter\Adapter'                   => 'Zend\Db\Adapter\AdapterServiceFactory'
        )
    ),

    'router' => array(
// Uncomment below to add routes
        'routes' => array(
            'loginalex' => array(
                'type' => 'Literal',
                'options' => array(
                    'route' => '/loginalex',
                    'defaults' => array(
                        '__NAMESPACE__' => 'LoginAlex\Controller',
                        'controller' => 'Login',
                        'action' => 'login',
                    )
                ),
//                'may_terminate' => true,
//                'child_routes' => array(
//                    'login' => array(
//                        'type' => 'literal',
//                        'options' => array(
//                            'route'    => '/login',
//                            'defaults' => array(
//                                'action'     => 'login'
//                            )
//                        )
//                    ),
//                ),

            )
        ),

    )
);

$tuto2 = array(
    'view_manager' => array(
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
    ),

    'controllers' => array(
        'invokables' => array(
            'LoginAlex\Controller\Login' => 'LoginAlex\Controller\LoginController',

        ),
    ),

    'service_manager' => array(

    ),

    'router' => array(
        'routes' => array(
            'loginalex' => array(
                'type' => 'literal',
                'options' => array(
                    'route'    => '/loginalex',
                    'defaults' => array(
                        '__NAMESPACE__' => 'LoginAlex\Controller',
                        'controller' => 'Login',
                        'action' => 'login',
                    )
                ),
//                // Defines that "/news" can be matched on its own without a child route being matched
//                'may_terminate' => true,
//                'child_routes' => array(
//                    'archive' => array(
//                        'type' => 'literal',
//                        'options' => array(
//                            'route'    => '/alex',
//                            'defaults' => array(
//                                'action'     => 'alex',
//                            ),
//                        ),
//                    ),
//                )
            ),
        )
    ),
);

return $tuto2;