<?php

/**
 * Generated by ZF2ModuleCreator
 */

return array(

    'view_manager' => array(
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
    ),

    'controllers' => array(
//        'invokables' => array(
//            'Test\Controller\Login' => 'Test\Controller\LoginController',
//
//        ),
        'factories' => array(
            'Test\Controller\Login'      => 'Test\Factory\LoginControllerFactory',
        )
    ),

    'service_manager' => array(
        'factories' => array(
            'Test\Mapper\LoginMapperInterface'   => 'Test\Factory\ZendDbSqlMapperFactory',
            'Test\Service\LoginServiceInterface' => 'Test\Factory\LoginServiceFactory',
            'Zend\Db\Adapter\Adapter'           => 'Zend\Db\Adapter\AdapterServiceFactory'
        )
    ),

    'router' => array(
        'routes' => array(
            'test' => array(
                'type' => 'Literal',
                'options' => array(
                    'route' => '/test',
                    'defaults' => array(
                        '__NAMESPACE__' => 'Test\Controller',
                        'controller' => 'Login',
                        'action' => 'login',
                    )
                ),
                'may_terminate' => true,
                'child_routes' => array(

                    'archive' => array(
                        'type' => 'literal',
                        'options' => array(
                            'route'    => '/login',
                            'defaults' => array(
                                'action'     => 'login',
                            ),
                        ),
                    ),

                    'success' => array(
                        'type'    => 'Literal',
                        'options' => array(
                            'route'    => '/success',
                            'defaults' => array(
                                'action'        => 'success',
                            ),
                        ),
                    ),
                ),

            )
        ),

    )
);