<h1>WriteController::editAction()</h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('comercializador/edit', array(), true));
$form->prepare();

$form->get('submit')->setValue('Update Comercializador');

echo $this->form()->openTag($form);
?>

    <div class="form_element">
        <?php
        $name = $form->get('post-fieldset')->get('username');
        echo $this->formRow($name);
        ?></div>

    <div class="form_element">
        <?php
        $subject = $form->get('post-fieldset')->get('nombre');
        echo $this->formRow($subject);
        ?></div>

    <div class="form_element">
        <?php
        $subject = $form->get('post-fieldset')->get('mail');
        echo $this->formRow($subject);
        ?></div>

    <div class="form_element">
        <?php
        $subject = $form->get('post-fieldset')->get('descripcion');
        echo $this->formRow($subject);
        ?></div>

<?php echo $this->formElement($form->get('submit')) ?>

<?php

//echo $this->formCollection($form);

echo $this->form()->closeTag();

